import type { EditorThemeClasses } from 'lexical'

export const editorTheme: EditorThemeClasses = {
  paragraph: 'kb-paragraph',
  quote: 'kb-quote',
  heading: {
    h1: 'kb-h1',
    h2: 'kb-h2',
    h3: 'kb-h3',
  },
  list: {
    ul: 'kb-ul',
    ol: 'kb-ol',
    listitem: 'kb-li',
    nested: {
      listitem: 'kb-nested-li',
    },
  },
  link: 'kb-link',
  text: {
    bold: 'kb-bold',
    italic: 'kb-italic',
    underline: 'kb-underline',
    strikethrough: 'kb-strikethrough',
    code: 'kb-text-code',
  },
  code: 'kb-code-block',
  codeHighlight: {
    atrule: 'kb-token-attr',
    attr: 'kb-token-attr',
    boolean: 'kb-token-property',
    builtin: 'kb-token-selector',
    cdata: 'kb-token-comment',
    char: 'kb-token-selector',
    class: 'kb-token-function',
    'class-name': 'kb-token-function',
    comment: 'kb-token-comment',
    constant: 'kb-token-property',
    deleted: 'kb-token-property',
    doctype: 'kb-token-comment',
    entity: 'kb-token-operator',
    function: 'kb-token-function',
    important: 'kb-token-variable',
    inserted: 'kb-token-selector',
    keyword: 'kb-token-attr',
    namespace: 'kb-token-variable',
    number: 'kb-token-property',
    operator: 'kb-token-operator',
    prolog: 'kb-token-comment',
    property: 'kb-token-property',
    punctuation: 'kb-token-punctuation',
    regex: 'kb-token-variable',
    selector: 'kb-token-selector',
    string: 'kb-token-selector',
    symbol: 'kb-token-property',
    tag: 'kb-token-property',
    url: 'kb-token-operator',
    variable: 'kb-token-variable',
  },
}
